### ISSUE TITLE
What is the difference to the official xiaomi_miio component?

### ISSUE THREAD

**Issue by Golab** [syssi/xiaomi_airpurifier#110]
Hello, can you explain what the difference between your add on and integrated one in home assistant?

https://www.home-assistant.io/integrations/xiaomi_miio/

**Comment by syssi** [comment]
This custom component is more or less the beta version of the official component. Furthermore this custom components supports a bunch of additional devices which cannot be merged into the official component at the moment. The handling/values of the fan_speed property needs to be refactored first because this and the official component doesn't align with some architecture decisions anymore.

**Comment by ehn** [comment]
I was wondering the same thing. Probably others will too, and they may not immediately find this pinned issue. Created a pull request to add the explanation to the README in case that's helpful.
