### ISSUE TITLE
Attribute AQI doesn't provide a value if aqi=1 is measured

### ISSUE THREAD

**Issue by jbustdel** [syssi/xiaomi_airpurifier#170]
Since update to 0.6.6. the Aqi index of my Xiaomi Purifier 3H appears unavailible.

## System Health

version | core-2021.4.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.4.109
arch | x86_64
timezone | Europe/Madrid

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4838
Installed Version | 1.11.3
Stage | running
Available Repositories | 775
Installed Repositories | 19

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 29

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 5.13
-- | --
update_channel | stable
supervisor_version | supervisor-2021.03.9
docker_version | 19.03.15
disk_total | 219.4 GB
disk_used | 8.1 GB
healthy | true
supported | true
board | intel-nuc
supervisor_api | ok
version_api | ok
installed_addons | AdGuard Home (4.0.0), AirCast (3.0.0), AppDaemon 4 (0.5.1), Check Home Assistant configuration (3.6.0), Duck DNS (1.12.5), File editor (5.2.0), Home Assistant Google Drive Backup (0.103.1), Let's Encrypt (4.11.0), Samba share (9.3.0), Terminal & SSH (9.1.0), Node-RED (8.2.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 20
views | 20
mode | storage

</details>

**Comment by syssi** [comment]
This is a behaviour of `python-miio==0.5.5.*` and will be fixed with version 0.5.6 by https://github.com/rytilahti/python-miio/pull/1007.

**Comment by jbustdel** [comment]
Ok. Thanks

**Comment by syssi** [comment]
@jbustdel Is my assumption correct? The attribute `aqi` is visible at the fan entity but the value is sometimes `None` instead of `1`?

**Comment by jbustdel** [comment]
Yes. You are right. That is the problem.

**Comment by bobofruit1970** [comment]
Friends as a novice, I don't really understand how the amendment process works, so please be understanding. There was problem with Xiaomi H3 detected month ago "Attribute AQI doesn't provide a value if aqi = 1". If I can understand the problem was caused by a change that made little sense and the change will be undone. I can't use H3 automation for a month because of this bug. I waited a month for an update to the May HA version but nothing has improved. There seems to be still a bug in yesterday's HA update. Maybe I should take some steps to get this improved library to appear in my place? Am I doing something wrong with my HA? The solution has been known for a month but my HA refuses to import this patch for some reason. Should I still wait for the next update in a month or should I change something in my HA configuration to import the patch and use the Xiaomi H3 automaton as it used to be. Can someone confirm that this previously damaged python-miio == 0.5.5 library has been repaired and imported into HA? And if it hasn't been imported yet, maybe someone knows when it will be fixed and released as an HA update?
