### ISSUE TITLE
AQI data is not displayed correctly.

### ISSUE THREAD

**Issue by jonathanathe** [syssi/xiaomi_airpurifier#178]
First of all, I would like to thank you for the work you are doing, as this integration is very useful.
My problem is that since 2 or 3 updates ago the AQI field is not displayed correctly for example currently I get 1 AQI, but since the integration I get 20 AQI. I hope you can help me.  Thank you.

Regards.

**Comment by syssi** [comment]
Could you compare the value with the value at the Mi Home app or could you query the device by `python-miio` (`miiocli`). The next step is to increase the log level to debug and provide some logs. 

The AQI=1 returns `None` issue is well known and already fixed upstream. Your AQI=20 issue is new to me.

**Comment by igoree** [comment]
AQI=20 is a known issue with zhimi.airpurifier.ma4 (probably other airpurifiers as well). I get this value every time I unplug the power cable and then the value stays the same for about 30 minutes. This problem is not an xiaomi_airpurifier integration specific problem, I also encounter it in MiHome app. But MiHome app uses a workaround for this problem because when I open the device plugin on the local network, the AQI immediately becomes correct.

**Comment by andrew-yu** [comment]
I have Xiaomi Purifier 3 (zhimi.airpurifier.ma4). All works good, except AQI. AQI updates randomly, one per hour, few hours, 10 minutes or so. Most of the time AQI is '-'. In Mi Home App AQI updates normally.

**Comment by syssi** [comment]
All measurements are retrieved periodically (`scan_interval`). If the value doesn't change the `last_updated` attribute will increase. The attribute is updated only if the value has changed.

At the moment the AQI value "1" isn't populated properly. You see `-` instead. For further support debug logs are required.

**Comment by jonathanathe** [comment]
Hi, I see that it is now working correctly, I reintegrated everything and it seems to be working. Thank you for your help.

**Comment by andrew-yu** [comment]
> If the value doesn't change the `last_updated` attribute will increase. The attribute is updated only if the value has changed.
Probably this is not the best thing, because value was updated but not changed, so  `last_updated` should be reset.
> At the moment the AQI value "1" isn't populated properly. You see `-` instead. For further support debug logs are required.
Probably, this is another not the best thing:
1. You get different value, than your device show
2. You need more complicated automations, because AQI sensor can show numeriacal or non-numerical values.

**Comment by andrew-yu** [comment]
> All measurements are retrieved periodically (`scan_interval`). If the value doesn't change the `last_updated` attribute will increase. The attribute is updated only if the value has changed.
Probably this is not the best thing because value was updated, but not changed, so `last_updated` should be reset.

> At the moment the AQI value "1" isn't populated properly. You see `-` instead. For further support debug logs are required.
Probably, this is another not the best thing:
1. You get different value, than your device show
2. You need more complicated automations, because AQI sensor can show numeriacal or non-numerical values.

**Comment by syssi** [comment]
> > All measurements are retrieved periodically (`scan_interval`). If the value doesn't change the `last_updated` attribute will increase. The attribute is updated only if the value has changed.
> 
> Probably this is not the best thing because value was updated, but not changed, so `last_updated` should be reset.

This is how Home Assistant works. This isn't a decision of the component.
 
> > At the moment the AQI value "1" isn't populated properly. You see `-` instead. For further support debug logs are required.
> Probably, this is another not the best thing:
> 
> 1. You get different value, than your device show
> 2. You need more complicated automations, because AQI sensor can show numeriacal or non-numerical values.

It's a **bug** and already fixed upstream cp. my first comment.

**Comment by andrew-yu** [comment]
Thank you!

**Comment by syssi** [comment]
@andrew-yu May be you should check my statement in detail. I'm not 100% sure about it because there a to attributes: `last_updated` and `last_changed`. May be im wrong!?

**Comment by andrew-yu** [comment]
will check it
