### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by bachulator** [syssi/xiaomi_airpurifier#18]
2018-01-29 10:33:31 ERROR (MainThread) [homeassistant.components.fan] Error while setting up platform xiaomi_miio  File "/config/custom_components/fan/xiaomi_miio.py", line 97, in async_setup_platform

Release: 0.4.0

**Comment by syssi** [comment]
Did you install the custom component because the official component is broken also? The miio stack is broken currently because of a changed API of construct (a dependency of python-miio). It will be fixed this week. I don't know a easy way for hassio users to enforce python-miio==master and construct==2.9.23.

**Comment by bachulator** [comment]
Frankly I didn't even realized there is official component. :) Was kinda sure that custom one is in production. But yes, built-in one is broken too. Thanks will wait for update of construct then.

Cheers.

**Comment by syssi** [comment]
Fixed (v0.4.1).
