### ISSUE TITLE
zhimi.airfresh.va2 doesn't work with ver 0.6.11

### ISSUE THREAD

**Issue by sumsethan** [syssi/xiaomi_airpurifier#187]
zhimi.airfresh.va2 doesn't work with new version 0.6.11 , but works fine with 0.6.9
 

installed by HACS on Hassio core-2021.5.1

**Comment by syssi** [comment]
Do you use additional custom components interfacing Xiaomi devices? Please make sure every custom component requiring `python-miio` requires the same version (`0.5.6`). As soon a single component downgrades the library the component cannot work anymore.

**Comment by Lemonadel** [comment]
Is there a posibility to make a new repo just for HASSIO? It’s impossible to get this or any other miio (even stock) component working because there  based on command “ha core check”:

construct==2.9.45
python-miio==0.5.3

These are from latest versions OS and HA.

Even when I downgrade in manifest.json it’s not possible to restart HA, as well as manually downloading 0.5.0 allows to only restart once, after that HA states that it could not find this component.
Even copying __pycache__ to latest version 0.6.11 does not fix it - after restart it’s broken.

**Comment by syssi** [comment]
Could you provide details how to reproduce the issue? Which HA core version do you use?

**Comment by Lemonadel** [comment]
I suppose all data might be helpful, so:
Host Operating System: Home Assistant OS 6.1
supervisor 2021.06.06
Board rpi4 (2GB one), armv7l
core: core-2021.6.6
python 3.8.9

About other components using Xiaomi miio… well, I have 1 custom_component installed manually to support vacuum cleaner ( STYJ02YM)
https://github.com/KrzysztofHajdamowicz/home-assistant-vacuum-styj02ym
it requires in manifest.js : 
construct==2.9.45
python-miio==0.5.3

and Xiaomi Cloud Map Extractor, which also have requirement of:
python-miio==0.5.3

**Comment by syssi** [comment]
Please make sure: Every custom component (using `python-miio`) must require the same and most recent `python-miio` release to avoid this conflict!

**Comment by Lemonadel** [comment]
You was right, there were issue with miio versions
