### ISSUE TITLE
Add support for zhimi.fan.za5

### ISSUE THREAD

**Issue by jacobhallgren** [syssi/xiaomi_airpurifier#192]
Hi please add support for mi fan 3 zhimi.fan.za5

EAN: 6970403201486

Thanks in advance.

**Comment by jimmyhawkin** [comment]
WOuld love to see sopport for this device aswell. I went ang bougt it thinking it was V3 pedestal only to see now when i extract the token thats thats not realy the case :(

So in a way i thought i had done the reserch to be able to add it to Homeassistant but dam.. 
So if you could find the time to add it so that the 3 ive gotten can work in home assistant. Then that would be great.

**Comment by syssi** [comment]
The ZA5 is supported of the custom component `xiaomi_fan` now: https://github.com/syssi/xiaomi_fan

Please give it a try!
