### ISSUE TITLE
Add deerma.humidifier.jsqs (MJJSQ03DY) support

### ISSUE THREAD

**Issue by NikolayBorisov** [syssi/xiaomi_airpurifier#202]
I bought Xiaomi Mijia Smart Sterilization Humidifier S witch identifying as deerma.humidifier.jsqs and its not supported.

If I specify model deerma.humidifier.mjjsq (or something else) then I got exception {'code': -9999, 'message': 'user ack timeout'}

**Comment by oopptt** [comment]
Hi guys. Same here, since some weeks ago my mjjsq stopped working. I have the following on my configuration.yaml:

model: deerma.humidifier.mjjsq

Log shows the following (humidifier is online and with correct token):

2021-08-30 11:43:56 ERROR (SyncWorker_0) [miio.miioprotocol] Got error when receiving: timed out
2021-08-30 11:43:56 ERROR (MainThread) [custom_components.xiaomi_miio_airpurifier.fan] Got exception while fetching the state: No response from the device

I have to use Mi Home app instead but I can't interact with HA which is really boring. It was working some releases before, I can make some tests if you request.

Regards.

**Comment by AlexeyTorch** [comment]
Good afternoon.
I am also very interested in support for deerma.humidifier.jsqs
If I can help you with something to add a device, I'm ready for any action (running commands in python_mio, dumps, providing access to my computer, or etc).

**Comment by AlexeyTorch** [comment]
PS:  Device  MIIOT Spec:
https://home.miot-spec.com/spec?type=urn%3Amiot-spec-v2%3Adevice%3Ahumidifier%3A0000A00E%3Adeerma-jsqs%3A1

**Comment by avadrag1** [comment]
I am also whaiting for suppotr deerma.humidifier.jsqs
Tell me if I can help with testing.

**Comment by inferusvv** [comment]
The same for me. I bought it yesterday, because it is marked as supported:

<img width="832" alt="Снимок экрана 2021-12-11 в 13 12 24" src="https://user-images.githubusercontent.com/3227120/145672824-7f773a76-4205-4b1c-aa02-4c11ac92ed9a.png">

But getting error:

> Got exception while fetching the state: {'code': -9999, 'message': 'user ack timeout'}
> Got exception while fetching the state: Unable to discover the device 192.168.1.31

**Comment by inferusvv** [comment]
I want to add that device is making "beep" sound before error log. It means that something is trying to happen (?)

**Comment by syssi** [comment]
Do you use the official component or this custom component?

**Comment by inferusvv** [comment]
@syssi Official is saying that device is not supported. So I tried this one. In issue https://github.com/syssi/xiaomi_airpurifier/issues/213 I found https://github.com/al-one/hass-xiaomi-miot which is works fine
